name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Lint HTML & CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Run HTMLHint
        run: htmlhint "src/*.html"

      - name: Run Stylelint
        run: stylelint "styles/*.css"

  build:
    name: Build Static Website
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Parcel
        run: npm install -g parcel-bundler

      - name: Build Website
        run: parcel build src/index.html --no-cache
